/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const flag: string;
declare const icon: string;
declare const large: string;

declare const __default_export__: {
	flag: typeof flag;
	icon: typeof icon;
	large: typeof large;
};
export default __default_export__;
