/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const flag: string;
declare const icon: string;
declare const large: string;

export {
	flag,
	icon,
	large
};
