/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const list: string;
declare const giant3: string;
declare const giant2: string;
declare const giant1: string;
declare const large2: string;
declare const large2Secondary: string;
declare const large1: string;
declare const large1Secondary: string;
declare const mediumBold: string;
declare const medium: string;
declare const mediumSecondary: string;
declare const regularBold: string;
declare const regular: string;
declare const regularSecondary: string;
declare const smallBold: string;
declare const small: string;
declare const smallSecondary: string;
declare const giantScreenLarge: string;
declare const largeScreenLarge: string;
declare const mediumScreenLarge: string;
declare const smallScreenLarge: string;
declare const giantScreenSmall: string;
declare const largeScreenSmall: string;
declare const mediumScreenSmall: string;
declare const smallScreenSmall: string;

export {
	list,
	giant3,
	giant2,
	giant1,
	large2,
	large2Secondary,
	large1,
	large1Secondary,
	mediumBold,
	medium,
	mediumSecondary,
	regularBold,
	regular,
	regularSecondary,
	smallBold,
	small,
	smallSecondary,
	giantScreenLarge,
	largeScreenLarge,
	mediumScreenLarge,
	smallScreenLarge,
	giantScreenSmall,
	largeScreenSmall,
	mediumScreenSmall,
	smallScreenSmall
};
