/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const list: string;
declare const giant3: string;
declare const giant2: string;
declare const giant1: string;
declare const large2: string;
declare const large2Secondary: string;
declare const large1: string;
declare const large1Secondary: string;
declare const mediumBold: string;
declare const medium: string;
declare const mediumSecondary: string;
declare const regularBold: string;
declare const regular: string;
declare const regularSecondary: string;
declare const smallBold: string;
declare const small: string;
declare const smallSecondary: string;
declare const giantScreenLarge: string;
declare const largeScreenLarge: string;
declare const mediumScreenLarge: string;
declare const smallScreenLarge: string;
declare const giantScreenSmall: string;
declare const largeScreenSmall: string;
declare const mediumScreenSmall: string;
declare const smallScreenSmall: string;

declare const __default_export__: {
	list: typeof list;
	giant3: typeof giant3;
	giant2: typeof giant2;
	giant1: typeof giant1;
	large2: typeof large2;
	large2Secondary: typeof large2Secondary;
	large1: typeof large1;
	large1Secondary: typeof large1Secondary;
	mediumBold: typeof mediumBold;
	medium: typeof medium;
	mediumSecondary: typeof mediumSecondary;
	regularBold: typeof regularBold;
	regular: typeof regular;
	regularSecondary: typeof regularSecondary;
	smallBold: typeof smallBold;
	small: typeof small;
	smallSecondary: typeof smallSecondary;
	giantScreenLarge: typeof giantScreenLarge;
	largeScreenLarge: typeof largeScreenLarge;
	mediumScreenLarge: typeof mediumScreenLarge;
	smallScreenLarge: typeof smallScreenLarge;
	giantScreenSmall: typeof giantScreenSmall;
	largeScreenSmall: typeof largeScreenSmall;
	mediumScreenSmall: typeof mediumScreenSmall;
	smallScreenSmall: typeof smallScreenSmall;
};
export default __default_export__;
