/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const item: string;
declare const list: string;

declare const __default_export__: {
	item: typeof item;
	list: typeof list;
};
export default __default_export__;
