/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-guaranteed-fit-filled-24"><circle cx="12" cy="12" r="12" fill="var(--color-background-success, #288034)"/><path fill-rule="evenodd" clip-rule="evenodd" d="M16.711 8.624a1 1 0 0 1 0 1.414l-5.338 5.339a1 1 0 0 1-1.415 0l-2.669-2.67a1 1 0 1 1 1.414-1.414l1.962 1.962 4.632-4.631a1 1 0 0 1 1.414 0Z" fill="var(--color-foreground-on-success, #FFFFFF)"/></symbol>`;

export const EbayIconGuaranteedFitFilled24: EbayIconComponent = props => (
    <EbayIcon {...props} name="guaranteedFitFilled24" __type="icon" __symbol={SYMBOL} />
);