/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-bank-20"><path d="M18 17.001a1 1 0 0 1 0 2H2a1 1 0 1 1 0-2h16Zm-1.5-3a1 1 0 1 1 0 2h-13a1 1 0 0 1 0-2h13Zm-10.501-7a1 1 0 0 1 1 1l.001 4a1 1 0 0 1-2 0l-.001-4a1 1 0 0 1 1-1Zm8.001 0a1 1 0 0 1 1 1v4a1 1 0 1 1-2 0v-4a1 1 0 0 1 1-1Zm-4 0a1 1 0 0 1 1 1v4a1 1 0 1 1-2 0V8a1 1 0 0 1 1-1ZM9.6.083a1 1 0 0 1 .924.066l6.5 4a1 1 0 0 1-.524 1.852h-13a1 1 0 0 1-.524-1.851l6.5-4.001.125-.066ZM7.033 4.001h5.936L10 2.174 7.032 4Z"/></symbol>`;

export const EbayIconBank20: EbayIconComponent = props => (
    <EbayIcon {...props} name="bank20" __type="icon" __symbol={SYMBOL} />
);