/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-adjust-price-down-24"><path d="M7.905 1a1 1 0 1 1 0 1.999H5a2.001 2.001 0 0 0-2.001 2L3 11.162a1 1 0 0 0 .299.713l8.993 8.84a1.001 1.001 0 0 0 1.41-.006l7.003-7.015a1 1 0 0 0 .007-1.406l-3.445-3.507a1 1 0 1 1 1.427-1.4l3.446 3.507a2.997 2.997 0 0 1-.019 4.218l-7.003 7.015a3.003 3.003 0 0 1-4.23.02L1.897 13.3A3 3 0 0 1 1 11.162V5a4 4 0 0 1 4.001-4h2.904Zm5.188 1.1a1 1 0 0 1 1 1v10.45l1.793-1.793A1 1 0 1 1 17.3 13.17l-3.5 3.5a1 1 0 0 1-1.414 0l-3.5-3.5a1 1 0 1 1 1.414-1.414l1.793 1.793V3.1a1 1 0 0 1 1-1Z"/></symbol>`;

export const EbayIconAdjustPriceDown24: EbayIconComponent = props => (
    <EbayIcon {...props} name="adjustPriceDown24" __type="icon" __symbol={SYMBOL} />
);