/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-top-service-filled-16"><path d="M12.501 0a2.5 2.5 0 0 1 2.5 2.5v11.17c0 1.731-1.82 2.86-3.371 2.09l-3.48-1.727a.334.334 0 0 0-.296 0L4.37 15.761C2.82 16.53 1 15.4 1 13.67L1.001 2.5a2.5 2.5 0 0 1 2.5-2.5h9Z" fill="#0968F6"/><path fill-rule="evenodd" clip-rule="evenodd" d="M7.347 3.373a.76.76 0 0 1 1.304 0l.975 1.624 1.778.399a.76.76 0 0 1 .414 1.233l-1.176 1.386.258 2.135a.76.76 0 0 1-1.117.76L8 9.943l-1.785.967a.76.76 0 0 1-1.117-.76l.259-2.135L4.18 6.629a.76.76 0 0 1 .414-1.233l1.778-.4.975-1.623ZM8 5.2l-.673 1.12-1.212.272.808.952-.165 1.365 1.24-.671 1.241.671-.165-1.365.808-.952L8.67 6.32 8 5.201Z" fill="#fff"/></symbol>`;

export const EbayIconTopServiceFilled16: EbayIconComponent = props => (
    <EbayIcon {...props} name="topServiceFilled16" __type="icon" __symbol={SYMBOL} />
);