/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-live-broadcast-24"><path d="M4.854 2.359a1 1 0 0 1 1.193 1.605A9.986 9.986 0 0 0 2 12.001a9.985 9.985 0 0 0 4.046 8.035 1 1 0 1 1-1.192 1.605A11.984 11.984 0 0 1 0 12.001c0-3.952 1.91-7.457 4.854-9.642Zm12.893.207a1 1 0 0 1 1.398-.207A11.985 11.985 0 0 1 24 12c0 3.95-1.911 7.455-4.855 9.64a1 1 0 0 1-1.19-1.605A9.985 9.985 0 0 0 22 12a9.987 9.987 0 0 0-4.047-8.036 1 1 0 0 1-.206-1.398ZM7.4 6.726a1 1 0 0 1 1.315 1.508A4.986 4.986 0 0 0 7 12.002c0 1.504.663 2.852 1.715 3.77A1 1 0 0 1 7.4 17.279 6.987 6.987 0 0 1 5 12.002c0-2.105.93-3.994 2.4-5.276Zm7.791.097a1 1 0 0 1 1.41-.097 6.989 6.989 0 0 1 2.4 5.276 6.987 6.987 0 0 1-2.4 5.277 1 1 0 0 1-1.315-1.507A4.988 4.988 0 0 0 17 12.002c0-1.503-.662-2.85-1.714-3.768a1 1 0 0 1-.096-1.411ZM12 10a2 2 0 1 1 0 4 2 2 0 0 1 0-4Z"/></symbol>`;

export const EbayIconLiveBroadcast24: EbayIconComponent = props => (
    <EbayIcon {...props} name="liveBroadcast24" __type="icon" __symbol={SYMBOL} />
);