/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 12 12" id="icon-tick-12"><path d="M9.22 2.845a.75.75 0 1 1 1.06 1.06l-5.25 5.25a.75.75 0 0 1-1.06 0l-2.25-2.25a.75.75 0 1 1 1.06-1.06l1.72 1.72 4.72-4.72Z"/></symbol>`;

export const EbayIconTick12: EbayIconComponent = props => (
    <EbayIcon {...props} name="tick12" __type="icon" __symbol={SYMBOL} />
);