/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-stop-16"><rect x="1" y="1" width="14" height="14" rx="3"/></symbol>`;

export const EbayIconStop16: EbayIconComponent = props => (
    <EbayIcon {...props} name="stop16" __type="icon" __symbol={SYMBOL} />
);