/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 50 32" id="icon-bank-of-america-32-colored"><rect x=".5" y=".5" width="49" height="31" rx="1.5" fill="#fff" stroke="#191919" stroke-width="1"/><path d="M24.938 25.102c5.361-4.614 12.717-8.977 16.832-10.598-.624-.374-1.621-.998-2.743-1.621-5.237 1.745-11.471 5.61-16.957 9.975.998.748 1.87 1.496 2.868 2.244Z" fill="#E31D34"/><path d="M22.444 12.758a31.718 31.718 0 0 0-2.244-.997c-1.995.997-4.614 2.493-7.855 4.862.748.374 1.496.873 2.244 1.247 2.494-1.87 5.112-3.616 7.855-5.112Z" fill="#1E2C69"/><path d="M27.181 10.638c-.997-.499-4.239-1.746-6.608-2.244-.623.249-1.62.623-2.244.872.873.25 3.99 1.122 6.608 2.37.624-.375 1.621-.749 2.244-.998Z" fill="#E31D34"/><path d="M15.96 10.265c-2.992 1.371-6.109 3.241-7.73 4.364.624.249 1.247.498 1.995.872 3.74-2.493 6.733-4.114 7.855-4.613-.872-.25-1.62-.499-2.12-.623Z" fill="#1E2C69"/><path d="M29.427 9.766c.623-.25 1.496-.374 2.12-.623-1.995-.873-4.489-1.746-6.733-2.245-.374.125-1.372.374-2.12.624.873.25 3.367.748 6.733 2.244Zm-12.468 9.476c.748.498 1.62 1.122 2.494 1.745 5.486-4.239 10.972-7.605 16.956-9.475a23.255 23.255 0 0 1-2.493-1.247c-3.492.872-9.725 3.366-16.957 8.977Z" fill="#E31D34"/></symbol>`;

export const EbayIconBankOfAmerica32Colored: EbayIconComponent = props => (
    <EbayIcon {...props} name="bankOfAmerica32Colored" __type="icon" __symbol={SYMBOL} />
);