/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 64 64" id="icon-locker-64"><path fill-rule="evenodd" clip-rule="evenodd" d="M56.137 2A7.864 7.864 0 0 1 64 9.863V47.41c0 3.7-2.557 6.802-6 7.639V57a4 4 0 0 1-8 0v-1.727H14V57a4 4 0 0 1-8 0v-1.952a7.865 7.865 0 0 1-6-7.639V9.863A7.864 7.864 0 0 1 7.863 2h48.274ZM34.5 50.273h21.637A2.864 2.864 0 0 0 59 47.409V9.863A2.864 2.864 0 0 0 56.137 7H34.5v43.273ZM7.863 7A2.864 2.864 0 0 0 5 9.863V47.41a2.864 2.864 0 0 0 2.863 2.864H29.5V7H7.863Zm4.66 22.505a4.023 4.023 0 1 1 0 8.046 4.023 4.023 0 0 1 0-8.046Zm29.5-.001a4.023 4.023 0 1 1 0 8.046 4.023 4.023 0 0 1 0-8.046ZM23.5 18.004a2.5 2.5 0 0 1 0 5H11a2.5 2.5 0 0 1 0-5h12.5Zm29.5 0a2.5 2.5 0 0 1 0 5H40.5a2.5 2.5 0 0 1 0-5H53Zm-29.5-8a2.5 2.5 0 0 1 0 5H11a2.5 2.5 0 0 1 0-5h12.5Zm29.5 0a2.5 2.5 0 0 1 0 5H40.5a2.5 2.5 0 0 1 0-5H53Z"/></symbol>`;

export const EbayIconLocker64: EbayIconComponent = props => (
    <EbayIcon {...props} name="locker64" __type="icon" __symbol={SYMBOL} />
);