/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-ai-summary-20"><path d="M9.5 1a1 1 0 1 1 0 2H6a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-4.5a1 1 0 1 1 2 0V16a3 3 0 0 1-3 3H6a3 3 0 0 1-3-3V4a3 3 0 0 1 3-3h3.5ZM11 12a1 1 0 1 1 0 2H8a1 1 0 1 1 0-2h3Zm1-4a1 1 0 1 1 0 2H8a1 1 0 0 1 0-2h4ZM14.857.64c.184-.853 1.402-.853 1.585 0l.303 1.41c.13.603.601 1.075 1.204 1.205l1.41.303c.854.183.854 1.401 0 1.585l-1.41.302a1.57 1.57 0 0 0-1.204 1.204l-.303 1.41c-.183.854-1.401.854-1.585 0l-.302-1.41a1.57 1.57 0 0 0-1.204-1.204l-1.41-.302c-.854-.184-.854-1.402 0-1.585l1.41-.303a1.57 1.57 0 0 0 1.204-1.205l.302-1.41Z"/></symbol>`;

export const EbayIconAiSummary20: EbayIconComponent = props => (
    <EbayIcon {...props} name="aiSummary20" __type="icon" __symbol={SYMBOL} />
);