/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-ai-summary-16"><path d="M7 1a1 1 0 0 1 0 2H4.5a.5.5 0 0 0-.5.5v10a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 .5-.5V9a1 1 0 1 1 2 0v4.5a2.5 2.5 0 0 1-2.5 2.5h-7A2.5 2.5 0 0 1 2 13.5v-10A2.5 2.5 0 0 1 4.5 1H7Zm1.5 9a.75.75 0 0 1 0 1.5h-2a.75.75 0 0 1 0-1.5h2Zm1-3a.75.75 0 1 1 0 1.5h-3a.75.75 0 0 1 0-1.5h3ZM12.184.458c.13-.61 1.001-.61 1.132 0l.229 1.063c.1.468.466.834.934.934l1.063.228c.61.132.61 1.002 0 1.133l-1.063.229c-.468.1-.834.466-.934.933l-.229 1.064c-.13.61-1.001.61-1.132 0l-.229-1.064a1.217 1.217 0 0 0-.934-.933l-1.063-.229c-.61-.13-.61-1.001 0-1.133l1.063-.228c.468-.1.834-.466.934-.934l.229-1.063Z"/></symbol>`;

export const EbayIconAiSummary16: EbayIconComponent = props => (
    <EbayIcon {...props} name="aiSummary16" __type="icon" __symbol={SYMBOL} />
);