/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 12 12" id="icon-reply-chat-12"><path d="M6 7.5A5.25 5.25 0 0 1 .75 2.25a.75.75 0 0 1 1.5 0A3.75 3.75 0 0 0 6 6h3.44L7.72 4.28a.75.75 0 0 1 1.06-1.06l3 3a.75.75 0 0 1 0 1.06l-3 3a.75.75 0 1 1-1.06-1.06L9.44 7.5H6Z"/></symbol>`;

export const EbayIconReplyChat12: EbayIconComponent = props => (
    <EbayIcon {...props} name="replyChat12" __type="icon" __symbol={SYMBOL} />
);