/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-markdown-16"><path fill-rule="evenodd" clip-rule="evenodd" d="M2.046 4.502a.996.996 0 0 1 .802.466L4.5 7.446l1.668-2.5a.994.994 0 0 1 .54-.403l.014-.003a.993.993 0 0 1 .272-.04h.008l.04.002a1 1 0 0 1 .959.998v5a1 1 0 0 1-2 0V8.8l-.669 1.005a1.004 1.004 0 0 1-.107.133l-.018.018a.993.993 0 0 1-.331.22l-.031.01a.725.725 0 0 1-.06.022l-.047.012-.045.01c-.01.003-.021.004-.032.005a1 1 0 0 1-.415-.02l-.031-.007-.06-.021-.033-.012-.021-.01a.993.993 0 0 1-.308-.209.992.992 0 0 1-.131-.16l-.66-.99V10.5a1 1 0 0 1-2 0V5.543a.998.998 0 0 1 .77-1.017l.038-.008c.013-.003.026-.004.04-.006l.052-.008a1 1 0 0 1 .144-.002ZM12 4.5a1 1 0 0 1 1 1v2.581l.29-.289a1.001 1.001 0 0 1 1.414 1.416l-1.952 1.948a.997.997 0 0 1-1.495.011L9.292 9.208a1 1 0 0 1 1.412-1.416l.297.295V5.5a1 1 0 0 1 1-1Z"/></symbol>`;

export const EbayIconMarkdown16: EbayIconComponent = props => (
    <EbayIcon {...props} name="markdown16" __type="icon" __symbol={SYMBOL} />
);