/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-stop-20"><rect x="2" y="2" width="16" height="16" rx="3"/></symbol>`;

export const EbayIconStop20: EbayIconComponent = props => (
    <EbayIcon {...props} name="stop20" __type="icon" __symbol={SYMBOL} />
);