/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 12 12" id="icon-pin-12"><path d="M4.922.381A.751.751 0 0 1 5.945.097l4.85 2.745a.75.75 0 0 1-.74 1.306L9.6 3.89 8.28 6.152l.203 1.415c.029.2-.005.407-.096.589l-.442.882a.8.8 0 0 1-1.104.342l-1.557-.865L3.5 11.623a.75.75 0 1 1-1.301-.746l1.771-3.09-1.543-.858A.8.8 0 0 1 2.1 5.871l.438-.875a1 1 0 0 1 .5-.471l1.427-.614 1.22-2.237-.48-.27A.751.751 0 0 1 4.923.38Zm.745 4.463a.801.801 0 0 1-.387.353l-1.482.634-.056.11 3.187 1.772.045-.089-.214-1.5a.802.802 0 0 1 .1-.517L8.295 3.15l-1.302-.738-1.325 2.431Z"/></symbol>`;

export const EbayIconPin12: EbayIconComponent = props => (
    <EbayIcon {...props} name="pin12" __type="icon" __symbol={SYMBOL} />
);