/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-locker-24"><path d="M21 1a3 3 0 0 1 3 3v14a2.998 2.998 0 0 1-2 2.825v.675a1.5 1.5 0 0 1-3 0V21H5v.5a1.5 1.5 0 0 1-3 0v-.675A2.998 2.998 0 0 1 0 18V4a3 3 0 0 1 3-3h18Zm-8 18h8a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1h-8v16ZM3 3a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h8V3H3Zm1.5 8a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Zm11 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM9 7a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2h5Zm11 0a1 1 0 1 1 0 2h-5a1 1 0 1 1 0-2h5ZM9 4a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2h5Zm11 0a1 1 0 1 1 0 2h-5a1 1 0 1 1 0-2h5Z"/></symbol>`;

export const EbayIconLocker24: EbayIconComponent = props => (
    <EbayIcon {...props} name="locker24" __type="icon" __symbol={SYMBOL} />
);