/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 12" id="icon-chase-12-colored"><rect width="20" height="12" rx="2" fill="#005EB8"/><path d="M8.773 1.688a.304.304 0 0 0-.305.304v2.135h5.638l-2.567-2.44H8.773Zm5.54 3.085a.303.303 0 0 0-.305-.304h-2.134v5.64l2.438-2.57V4.773Zm-3.085 5.54a.305.305 0 0 0 .304-.306V7.873H5.894l2.567 2.44h2.767Zm-5.54-3.085c0 .168.136.305.304.305h2.134v-5.64L5.688 4.462v2.766Z" fill="#fff"/></symbol>`;

export const EbayIconChase12Colored: EbayIconComponent = props => (
    <EbayIcon {...props} name="chase12Colored" __type="icon" __symbol={SYMBOL} />
);