/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-top-service-filled-24"><path d="M19 0a3 3 0 0 1 3 3v17.99c0 2.42-2.72 3.844-4.71 2.464l-4.717-3.271a1 1 0 0 0-1.14 0L6.71 23.457C4.719 24.837 2 23.413 2 20.992V3a3 3 0 0 1 3-3h14Z" fill="var(--color-background-accent, #0968f6)"/><path fill-rule="evenodd" clip-rule="evenodd" d="M10.713 4.737a1.5 1.5 0 0 1 2.574 0l1.261 2.107 2.282.514a1.5 1.5 0 0 1 .817 2.432l-1.511 1.787.33 2.743c.146 1.21-1.135 2.079-2.205 1.497L12 14.589l-2.26 1.228c-1.07.582-2.352-.288-2.206-1.497l.33-2.743-1.51-1.787a1.5 1.5 0 0 1 .816-2.432l2.282-.514 1.26-2.107ZM12 6.48l-1.03 1.721a1.1 1.1 0 0 1-.702.509l-1.855.417 1.232 1.457a1.1 1.1 0 0 1 .252.842l-.261 2.17 1.839-1a1.1 1.1 0 0 1 1.05 0l1.84 1-.262-2.17a1.1 1.1 0 0 1 .252-.842l1.232-1.457-1.854-.417a1.1 1.1 0 0 1-.703-.509L12 6.481Z" fill="var(--color-foreground-on-accent, #ffffff)"/></symbol>`;

export const EbayIconTopServiceFilled24: EbayIconComponent = props => (
    <EbayIcon {...props} name="topServiceFilled24" __type="icon" __symbol={SYMBOL} />
);