/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-rotate-16"><path d="M8.793.293a1 1 0 1 1 1.414 1.414L9.914 2H10c3.712 0 6 3.04 6 6.5a6.5 6.5 0 0 1-10.24 5.317 1 1 0 0 1 1.153-1.634A4.5 4.5 0 0 0 14 8.5C14 5.884 12.363 4 10 4h-.086l.293.293a1 1 0 1 1-1.414 1.414l-2-2a1 1 0 0 1 0-1.414l2-2ZM3.119 4.225a1 1 0 0 1 1.338.068l2.75 2.75a1 1 0 0 1 0 1.414l-2.75 2.75a1 1 0 0 1-1.414 0l-2.75-2.75a1 1 0 0 1 0-1.414l2.75-2.75.076-.068ZM2.414 7.75 3.75 9.086 5.086 7.75 3.75 6.414 2.414 7.75Z"/></symbol>`;

export const EbayIconRotate16: EbayIconComponent = props => (
    <EbayIcon {...props} name="rotate16" __type="icon" __symbol={SYMBOL} />
);