/* This file is autogenerated, do not edit - it will be overwritten anyway */

import React from "react";
import EbayIcon from "../icon";
import type { EbayIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-stop-24"><rect x="2" y="2" width="20" height="20" rx="4"/></symbol>`;

export const EbayIconStop24: EbayIconComponent = props => (
    <EbayIcon {...props} name="stop24" __type="icon" __symbol={SYMBOL} />
);