/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const footer: string;
declare const content: string;
declare const column: string;
declare const brand: string;
declare const brandTitle: string;
declare const end: string;

export {
	footer,
	content,
	column,
	brand,
	brandTitle,
	end
};
