/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const footer: string;
declare const content: string;
declare const column: string;
declare const brand: string;
declare const brandTitle: string;

export {
	footer,
	content,
	column,
	brand,
	brandTitle
};

declare const __default_export__: {
	footer: typeof footer;
	content: typeof content;
	column: typeof column;
	brand: typeof brand;
	brandTitle: typeof brandTitle;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic3R5bGUubW9kdWxlLnNjc3MuZC50cyIsInNvdXJjZXMiOlsic3R5bGUubW9kdWxlLnNjc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FDQTtjQXlDQTtjQWdCQTtjQUtBO2NBZ0JBOzs7Q0E5RUE7Q0F5Q0E7Q0FnQkE7Q0FLQTtDQWdCQTs7OztDQTlFQTtDQXlDQTtDQWdCQTtDQUtBO0NBZ0JBOzsifQ==
