/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const footer: string;
declare const content: string;
declare const column: string;
declare const brand: string;
declare const brandTitle: string;

declare const __default_export__: {
	footer: typeof footer;
	content: typeof content;
	column: typeof column;
	brand: typeof brand;
	brandTitle: typeof brandTitle;
};
export default __default_export__;
