/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const breadcrumbs: string;

declare const __default_export__: {
	breadcrumbs: typeof breadcrumbs;
};
export default __default_export__;
