// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-adjust-price-up-24"><path d="M7.905 1a1 1 0 1 1 0 1.999H5a2.001 2.001 0 0 0-2.001 2L3 11.162a1 1 0 0 0 .299.713l8.993 8.84a1.001 1.001 0 0 0 1.41-.006l7.003-7.015a1 1 0 0 0 .007-1.406l-1.519-1.546a1 1 0 1 1 1.427-1.4l1.52 1.546a2.997 2.997 0 0 1-.019 4.218l-7.003 7.015a3.003 3.003 0 0 1-4.23.02L1.897 13.3A3 3 0 0 1 1 11.162V5a4 4 0 0 1 4.001-4h2.904Zm4.389 1.313a1 1 0 0 1 1.414 0l3.5 3.5a1 1 0 1 1-1.414 1.414L14 5.434v9.649a1 1 0 0 1-2 0v-9.65l-1.793 1.794a1 1 0 1 1-1.414-1.415l3.5-3.5Z"/></symbol>`;

export function EvoIconAdjustPriceUp24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="adjustPriceUp24" __symbol={SYMBOL} />;
}
