// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-ai-mobile-20"><path d="M9 1a1 1 0 0 1 0 2H7a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-4.5a1 1 0 1 1 2 0V16a3 3 0 0 1-3 3H7a3 3 0 0 1-3-3V4a3 3 0 0 1 3-3h2Zm1.75 13a1 1 0 1 1 0 2h-1.5a1 1 0 0 1 0-2h1.5ZM14.207.64c.184-.854 1.4-.854 1.584 0l.303 1.41a1.57 1.57 0 0 0 1.205 1.204l1.41.303c.853.183.853 1.401 0 1.585l-1.41.302a1.57 1.57 0 0 0-1.205 1.204l-.303 1.41c-.183.854-1.4.854-1.584 0l-.303-1.41A1.57 1.57 0 0 0 12.7 5.444l-1.41-.302c-.853-.184-.853-1.402 0-1.585l1.41-.303a1.57 1.57 0 0 0 1.205-1.204l.303-1.41Z"/></symbol>`;

export function EvoIconAiMobile20(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="aiMobile20" __symbol={SYMBOL} />;
}
