// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-auto-adjust-16"><path d="M5.98 4.343a1.501 1.501 0 0 1 2.008.102l7.572 7.573.103.114c.448.55.448 1.344 0 1.893l-.103.114-1.42 1.42-.114.104a1.501 1.501 0 0 1-2.007-.103L4.446 7.987a1.5 1.5 0 0 1 0-2.12l1.421-1.422.113-.102Zm2.9 5.249 4.2 4.199.713-.713-4.2-4.2-.713.714Zm-6.189.3a1 1 0 0 1 1.414 1.415l-.707.707A1 1 0 0 1 1.983 10.6l.707-.707Zm3.524-2.965 1.25 1.25.715-.712-1.251-1.251-.714.713ZM2 6a1 1 0 0 1 0 2H1a1 1 0 0 1 0-2h1Zm8.596-4.006a1 1 0 0 1 1.414 1.414l-.707.707a1 1 0 1 1-1.414-1.414l.707-.707Zm-9.053-.451a1 1 0 0 1 1.414 0l1 1a1 1 0 1 1-1.414 1.414l-1-1a1 1 0 0 1 0-1.414ZM7 0a1 1 0 0 1 1 1v1a1 1 0 0 1-2 0V1a1 1 0 0 1 1-1Z"/></symbol>`;

export function EvoIconAutoAdjust16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="autoAdjust16" __symbol={SYMBOL} />;
}
