// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-coupon-20"><path d="M16 3a3 3 0 0 1 3 3v2a1 1 0 0 1-1 1h-.5a1 1 0 1 0 0 2h.5a1 1 0 0 1 1 1v2a3 3 0 0 1-3 3H4a3 3 0 0 1-3-3v-2a1 1 0 0 1 1-1h.5a1 1 0 1 0 0-2H2a1 1 0 0 1-1-1V6a3 3 0 0 1 3-3h12ZM4 5a1 1 0 0 0-1 1v1.041a3.001 3.001 0 0 1 0 5.917V14a1 1 0 0 0 1 1h4v-1a1 1 0 1 1 2 0v1h6a1 1 0 0 0 1-1v-1.042a3 3 0 0 1 0-5.917V6a1 1 0 0 0-1-1h-6v1a1 1 0 0 1-2 0V5H4Zm5 3.5a1 1 0 0 1 1 1v1a1 1 0 1 1-2 0v-1a1 1 0 0 1 1-1Z"/></symbol>`;

export function EvoIconCoupon20(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="coupon20" __symbol={SYMBOL} />;
}
