// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-gift-20"><path d="M12.002 1a3 3 0 0 1 3 3c0 .351-.064.687-.175 1H17.2A1.8 1.8 0 0 1 19 6.8v1.9a1.8 1.8 0 0 1-1.8 1.8h-.198v5.833A2.668 2.668 0 0 1 14.335 19H5.669a2.667 2.667 0 0 1-2.667-2.667V10.5H2.8A1.8 1.8 0 0 1 1 8.7V6.8A1.8 1.8 0 0 1 2.8 5h2.376a3 3 0 0 1 2.826-4c.769 0 1.468.292 1.999.768A2.988 2.988 0 0 1 12.002 1Zm-7 15.333c0 .368.299.667.667.667h3.333v-6.5h-4v5.833Zm6 .667h3.333a.668.668 0 0 0 .667-.667V10.5h-4V17ZM3 8.5h6.002V7H3v1.5Zm8.002 0H17V7h-5.998v1.5Zm-3-5.5a1 1 0 0 0 0 2h1V4l-.006-.103A1 1 0 0 0 8.002 3Zm4 0a1 1 0 0 0-.995.897L11.002 4v1h1a1 1 0 0 0 0-2Z"/></symbol>`;

export function EvoIconGift20(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="gift20" __symbol={SYMBOL} />;
}
