// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-guaranteed-fit-filled-16"><circle cx="8" cy="8" r="8" fill="var(--color-background-success, #288034)"/><path d="M11.207 5.793a1 1 0 0 1 0 1.414l-3.5 3.5a1 1 0 0 1-1.414 0l-1.5-1.5a1 1 0 0 1 1.414-1.414L7 8.586l2.793-2.793a1 1 0 0 1 1.414 0Z" fill="var(--color-foreground-on-success, #FFFFFF)"/></symbol>`;

export function EvoIconGuaranteedFitFilled16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="guaranteedFitFilled16" __symbol={SYMBOL} />;
}
