// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-guaranteed-fit-filled-24"><circle cx="12" cy="12" r="12" fill="var(--color-background-success, #288034)"/><path fill-rule="evenodd" clip-rule="evenodd" d="M16.711 8.624a1 1 0 0 1 0 1.414l-5.338 5.339a1 1 0 0 1-1.415 0l-2.669-2.67a1 1 0 1 1 1.414-1.414l1.962 1.962 4.632-4.631a1 1 0 0 1 1.414 0Z" fill="var(--color-foreground-on-success, #FFFFFF)"/></symbol>`;

export function EvoIconGuaranteedFitFilled24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="guaranteedFitFilled24" __symbol={SYMBOL} />;
}
