// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-home-20"><path d="M7.686 1.904a3.416 3.416 0 0 1 4.63 0l5.717 5.268A3 3 0 0 1 19 9.378v7.373a2.25 2.25 0 0 1-2.25 2.25h-3a2.25 2.25 0 0 1-2.25-2.25v-3.25a.5.5 0 0 0-.5-.5H9a.5.5 0 0 0-.5.5v3.25a2.25 2.25 0 0 1-2.25 2.25h-3A2.25 2.25 0 0 1 1 16.751V9.378a3 3 0 0 1 .968-2.206l5.718-5.268Zm3.274 1.471c-.542-.5-1.378-.5-1.92 0L3.322 8.643A1 1 0 0 0 3 9.378v7.373c0 .138.112.25.25.25h3a.25.25 0 0 0 .25-.25v-3.25a2.5 2.5 0 0 1 2.5-2.5h2a2.5 2.5 0 0 1 2.5 2.5v3.25c0 .138.112.25.25.25h3a.25.25 0 0 0 .25-.25V9.378a1 1 0 0 0-.322-.735L10.96 3.375Z"/></symbol>`;

export function EvoIconHome20(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="home20" __symbol={SYMBOL} />;
}
