// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 12 12" id="icon-information-12"><path d="M6 5.25a.75.75 0 0 0-.75.75v2.25a.75.75 0 0 0 1.5 0V6A.75.75 0 0 0 6 5.25Zm.75-1.5a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z"/><path d="M0 6a6 6 0 1 1 12 0A6 6 0 0 1 0 6Zm1.5 0a4.5 4.5 0 1 0 9 0 4.5 4.5 0 0 0-9 0Z"/></symbol>`;

export function EvoIconInformation12(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="information12" __symbol={SYMBOL} />;
}
