// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-link-20"><path d="M4.633 8.683a1 1 0 0 1 1.414 1.414l-2.249 2.249A2.727 2.727 0 0 0 7.654 16.2L9.9 13.954a1 1 0 1 1 1.414 1.414l-2.247 2.247a4.726 4.726 0 0 1-6.684-6.683l2.249-2.25Zm6.16-.89a1.001 1.001 0 0 1 1.415 1.414l-3.002 3.002a1 1 0 0 1-1.414-1.415l3.001-3.001Zm.14-5.41a4.726 4.726 0 0 1 6.683 6.684l-2.252 2.25a1 1 0 1 1-1.413-1.414l2.251-2.25a2.727 2.727 0 0 0-3.855-3.855l-2.25 2.249a1 1 0 0 1-1.414-1.415l2.25-2.248Z"/></symbol>`;

export function EvoIconLink20(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="link20" __symbol={SYMBOL} />;
}
