// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-link-24"><path d="M5.975 10.29a1 1 0 0 1 1.414 1.414L4.016 15.08a3.47 3.47 0 0 0 4.906 4.907l3.372-3.373a1 1 0 0 1 1.414 1.414L10.336 21.4a5.469 5.469 0 1 1-7.734-7.736l3.373-3.374Zm7.312-.999a1 1 0 0 1 1.414 1.414l-3.998 4a1 1 0 0 1-1.414-1.416l3.998-3.998Zm.377-6.69a5.469 5.469 0 1 1 7.735 7.736l-3.374 3.373a1 1 0 1 1-1.414-1.416l3.373-3.372a3.47 3.47 0 0 0-4.906-4.906l-3.373 3.372a1 1 0 0 1-1.414-1.414l3.373-3.372Z"/></symbol>`;

export function EvoIconLink24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="link24" __symbol={SYMBOL} />;
}
