// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-live-broadcast-20"><path d="M4.158 1.883a1 1 0 0 1 1.17 1.623l-.037.026A7.988 7.988 0 0 0 2 10a7.99 7.99 0 0 0 3.327 6.495 1 1 0 1 1-1.169 1.622A9.99 9.99 0 0 1 0 10a9.988 9.988 0 0 1 4.112-8.083l.046-.034Zm10.288.226a1 1 0 0 1 1.396-.226l.046.034A9.988 9.988 0 0 1 20 10a9.99 9.99 0 0 1-4.158 8.117 1 1 0 0 1-1.17-1.622A7.99 7.99 0 0 0 18 10a7.989 7.989 0 0 0-3.291-6.468l-.037-.026a1 1 0 0 1-.226-1.397ZM6.098 5.442a1 1 0 0 1 1.301 1.52A3.99 3.99 0 0 0 6 10a3.99 3.99 0 0 0 1.396 3.036 1 1 0 0 1-1.303 1.518A5.99 5.99 0 0 1 4 10a5.99 5.99 0 0 1 2.098-4.559Zm6.394.11a1 1 0 0 1 1.41-.11A5.991 5.991 0 0 1 16 10.001a5.99 5.99 0 0 1-2.093 4.554 1 1 0 0 1-1.303-1.518A3.99 3.99 0 0 0 14 10.001a3.99 3.99 0 0 0-1.4-3.04 1 1 0 0 1-.108-1.41ZM10 8.335a1.667 1.667 0 1 1-.001 3.333A1.667 1.667 0 0 1 10 8.335Z"/></symbol>`;

export function EvoIconLiveBroadcast20(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="liveBroadcast20" __symbol={SYMBOL} />;
}
