// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-rotate-24"><path d="M15.293 1.293a1 1 0 1 1 1.414 1.414L15.414 4h.086c5.054 0 8.5 4.116 8.5 9a9 9 0 0 1-15.75 5.953 1 1 0 0 1 1.5-1.323A7 7 0 0 0 22 13c0-3.953-2.717-7-6.5-7h-.086l1.293 1.293a1 1 0 1 1-1.414 1.414l-3-3a1 1 0 0 1 0-1.414l3-3ZM5.369 4.225a1 1 0 0 1 1.338.068l5 5a1 1 0 0 1 0 1.414l-5 5a1 1 0 0 1-1.414 0l-5-5a1 1 0 0 1 0-1.414l5-5 .076-.068ZM2.414 10 6 13.586 9.586 10 6 6.414 2.414 10Z"/></symbol>`;

export function EvoIconRotate24(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="rotate24" __symbol={SYMBOL} />;
}
