// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-rotate-20"><path d="M12.598.818a1 1 0 1 1 1.463 1.364l-.77.825C17.37 3.16 20 6.559 20 10.5a7.5 7.5 0 0 1-12.912 5.192 1 1 0 0 1 1.443-1.385A5.5 5.5 0 0 0 18 10.5c0-3.033-1.92-5.33-4.69-5.49l.754.808a1 1 0 0 1-1.463 1.365l-2.333-2.5a1 1 0 0 1 0-1.364l2.33-2.5ZM4.37 3.224a1 1 0 0 1 1.338.069l4 4a1 1 0 0 1 0 1.414l-4 4a1 1 0 0 1-1.414 0l-4-4a1 1 0 0 1 0-1.414l4-4 .076-.069ZM2.414 8 5 10.586 7.586 8 5 5.414 2.414 8Z"/></symbol>`;

export function EvoIconRotate20(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="rotate20" __symbol={SYMBOL} />;
}
