// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 20 20" id="icon-stop-20"><rect x="2" y="2" width="16" height="16" rx="3"/></symbol>`;

export function EvoIconStop20(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="stop20" __symbol={SYMBOL} />;
}
