// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-stop-16"><rect x="1" y="1" width="14" height="14" rx="3"/></symbol>`;

export function EvoIconStop16(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="stop16" __symbol={SYMBOL} />;
}
