// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 12 12" id="icon-tick-12"><path d="M9.22 2.845a.75.75 0 1 1 1.06 1.06l-5.25 5.25a.75.75 0 0 1-1.06 0l-2.25-2.25a.75.75 0 1 1 1.06-1.06l1.72 1.72 4.72-4.72Z"/></symbol>`;

export function EvoIconTick12(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="tick12" __symbol={SYMBOL} />;
}
