// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 29 18" id="icon-wire-transfer-card-18-colored"><rect x=".5" y=".5" width="27.125" height="17" rx="1.5" fill="#fff" stroke="#191919" stroke-width="1"/><path d="M11.953 6.893a.527.527 0 0 1 .336.93l.002.002c-.595.497-.865 1.327-.865 2.408 0 1.704 1.231 2.988 2.636 2.988 1.406 0 2.637-1.284 2.637-2.988 0-1.08-.27-1.911-.865-2.408l.001-.002a.524.524 0 0 1 .337-.93h2.637c.873 0 1.582.708 1.582 1.582v4.219c0 .873-.709 1.581-1.582 1.581H9.316a1.582 1.582 0 0 1-1.582-1.582V8.476c0-.874.709-1.582 1.582-1.582h2.637ZM9.316 7.947a.527.527 0 0 0-.527.528v4.219c0 .29.236.527.527.527h2.26c-.747-.748-1.205-1.823-1.205-2.988 0-.806.133-1.607.494-2.286H9.316Zm7.944 0c.36.679.494 1.48.494 2.286 0 1.165-.459 2.24-1.204 2.988h2.259a.527.527 0 0 0 .527-.527v-4.22a.527.527 0 0 0-.527-.527h-1.55Zm-3.57-5.119a.528.528 0 0 1 .745 0l1.846 1.846a.528.528 0 0 1-.746.746l-.945-.945v4.838a.528.528 0 0 1-1.055 0V4.475l-.945.945a.528.528 0 0 1-.746-.746l1.846-1.846Z" fill="#191919"/></symbol>`;

export function EvoIconWireTransferCard18Colored(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="wireTransferCard18Colored" __symbol={SYMBOL} />;
}
