// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 50 32" id="icon-wire-transfer-card-32-colored"><rect x=".5" y=".5" width="49" height="31" rx="1.5" fill="#fff" stroke="#191919" stroke-width="1"/><path d="M21.25 12.254a.937.937 0 0 1 .6 1.657c-1.056.883-1.538 2.36-1.538 4.28 0 3.03 2.19 5.313 4.688 5.313 2.498 0 4.688-2.283 4.688-5.312 0-1.921-.482-3.398-1.539-4.28a.937.937 0 0 1 .602-1.657h4.686a2.813 2.813 0 0 1 2.813 2.812v7.5a2.813 2.813 0 0 1-2.813 2.812H16.564a2.813 2.813 0 0 1-2.813-2.812v-7.5a2.813 2.813 0 0 1 2.813-2.813h4.687Zm-4.688 1.875a.937.937 0 0 0-.937.938v7.5c0 .517.42.937.938.937h4.015c-1.326-1.33-2.14-3.24-2.14-5.312 0-1.433.237-2.857.878-4.063h-2.753Zm14.122 0c.641 1.206.878 2.63.878 4.063 0 2.071-.814 3.982-2.14 5.312h4.015c.518 0 .938-.42.938-.937v-7.5a.937.937 0 0 0-.938-.938h-2.753Zm-6.347-9.1a.938.938 0 0 1 1.326 0l3.281 3.28a.938.938 0 0 1-1.326 1.327l-1.68-1.68v8.6a.938.938 0 0 1-1.875 0v-8.6l-1.681 1.68a.938.938 0 0 1-1.326-1.326l3.28-3.282Z" fill="#191919"/></symbol>`;

export function EvoIconWireTransferCard32Colored(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="wireTransferCard32Colored" __symbol={SYMBOL} />;
}
