// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponentProps } from "./types";

const SYMBOL = `<symbol viewBox="0 0 19 12" id="icon-wire-transfer-card-12-colored"><rect x=".5" y=".5" width="17.75" height="11" rx="1.5" fill="#fff" stroke="#191919" stroke-width="1"/><path d="M7.969 4.594a.352.352 0 0 1 .224.62h.001c-.396.332-.577.886-.577 1.606 0 1.136.821 1.992 1.758 1.992s1.758-.856 1.758-1.992c0-.72-.18-1.274-.577-1.605v-.001a.35.35 0 0 1 .225-.62h1.758c.583 0 1.055.472 1.055 1.054v2.813c0 .582-.472 1.055-1.055 1.055H6.211A1.055 1.055 0 0 1 5.156 8.46V5.648c0-.582.472-1.054 1.055-1.054h1.758Zm-1.758.703a.352.352 0 0 0-.352.351v2.813c0 .194.158.351.352.351h1.51a2.822 2.822 0 0 1-.807-1.992c0-.537.09-1.07.33-1.523H6.211Zm5.295 0c.24.452.33.986.33 1.523 0 .778-.308 1.494-.807 1.992h1.51a.352.352 0 0 0 .352-.351V5.648a.352.352 0 0 0-.352-.351h-1.033Zm-2.064-3.51a.35.35 0 0 1 .182.097l1.23 1.23a.353.353 0 0 1-.498.498l-.63-.63v3.225a.352.352 0 0 1-.703 0V2.982l-.63.63a.353.353 0 0 1-.497-.498l1.23-1.23a.35.35 0 0 1 .316-.097Z" fill="#191919"/></symbol>`;

export function EvoIconWireTransferCard12Colored(props: EvoIconComponentProps) {
  return <EvoIcon {...props} __name="wireTransferCard12Colored" __symbol={SYMBOL} />;
}
