/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const badge: string;
declare const badge_Circle: string;
declare const component: string;
declare const tabs: string;
declare const pagination: string;

export {
	badge,
	component,
	tabs,
	pagination
};
