/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const header: string;
declare const link: string;

export {
	header,
	link
};

declare const __default_export__: {
	header: typeof header;
	link: typeof link;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic3R5bGUubW9kdWxlLnNjc3MuZC50cyIsInNvdXJjZXMiOlsic3R5bGUubW9kdWxlLnNjc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTtjQVlBOzs7Q0FaQTtDQVlBOzs7O0NBWkE7Q0FZQTs7In0=
