/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const header: string;
declare const link: string;

declare const __default_export__: {
	header: typeof header;
	link: typeof link;
};
export default __default_export__;
