// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-remove-16"><path d="M13 7H3a1 1 0 0 0 0 2h10a1 1 0 0 0 0-2Z"/></symbol>`;

export const EvoIconRemove16: EvoIconComponent = props => (
    <EvoIcon {...props} name="remove16" __symbol={SYMBOL} />
);
