// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-add-24"><path d="M21 11h-8V3a1 1 0 0 0-2 0v8H3a1 1 0 0 0 0 2h8v8a1 1 0 0 0 2 0v-8h8a1 1 0 0 0 0-2Z"/></symbol>`;

export const EvoIconAdd24: EvoIconComponent = props => (
    <EvoIcon {...props} name="add24" __symbol={SYMBOL} />
);
