// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 18 18" id="icon-radio-unchecked-18"><path fill-rule="evenodd" clip-rule="evenodd" d="M9 18A9 9 0 1 1 9 0a9 9 0 0 1 0 18ZM9 1a8 8 0 1 0 0 16A8 8 0 0 0 9 1Z"/></symbol>`;

export const EvoIconRadioUnchecked18: EvoIconComponent = props => (
    <EvoIcon {...props} name="radioUnchecked18" __symbol={SYMBOL} />
);
