// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-feedback-neutral-16"><path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0ZM6.125 5.125a1 1 0 0 0-1 1v3.75a1 1 0 0 0 1 1h3.75a1 1 0 0 0 1-1v-3.75a1 1 0 0 0-1-1h-3.75Z"/></symbol>`;

export const EvoIconFeedbackNeutral16: EvoIconComponent = props => (
    <EvoIcon {...props} name="feedbackNeutral16" __symbol={SYMBOL} />
);
