// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-move-24"><path d="M18.71 17.29 7.48 6H17a1 1 0 0 0 0-2H5a1 1 0 0 0-1 1v12a1 1 0 0 0 2 0V7.35l11.29 11.36A.999.999 0 0 0 18 19a.999.999 0 0 0 .71-1.71Z"/></symbol>`;

export const EvoIconMove24: EvoIconComponent = props => (
    <EvoIcon {...props} name="move24" __symbol={SYMBOL} />
);
