// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-yuan-24"><path d="M3.774 1.367a1 1 0 0 0-1.548 1.266L10.708 13H6a1 1 0 1 0 0 2h5v2H6a1 1 0 1 0 0 2h5v3a1 1 0 1 0 2 0v-3h5a1 1 0 1 0 0-2h-5v-2h5a1 1 0 1 0 0-2h-4.708l8.482-10.367a1 1 0 1 0-1.548-1.266L12 11.42 3.774 1.367Z"/></symbol>`;

export const EvoIconYuan24: EvoIconComponent = props => (
    <EvoIcon {...props} name="yuan24" __symbol={SYMBOL} />
);
