// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 16 16" id="icon-chevron-left-16"><path d="M3.293 8.708a1 1 0 0 1 0-1.415l6-6a1 1 0 0 1 1.414 1.414L5.414 8l5.293 5.293a1 1 0 0 1-1.414 1.414l-6-6Z"/></symbol>`;

export const EvoIconChevronLeft16: EvoIconComponent = props => (
    <EvoIcon {...props} name="chevronLeft16" __symbol={SYMBOL} />
);
