// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-full-view-filled-24"><path d="M2 3h20a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1Zm20 16H2a1 1 0 0 0 0 2h20a1 1 0 0 0 0-2Z"/></symbol>`;

export const EvoIconFullViewFilled24: EvoIconComponent = props => (
    <EvoIcon {...props} name="fullViewFilled24" __symbol={SYMBOL} />
);
