// AUTO-GENERATED by `importSVG` script (`scripts/import-svg.ts`)

import { EvoIcon } from "../icon";
import type { EvoIconComponent } from "./types";

const SYMBOL = `<symbol viewBox="0 0 24 24" id="icon-menu-24"><path d="M3 5h18a1 1 0 0 0 0-2H3a1 1 0 0 0 0 2Zm18 6H3a1 1 0 0 0 0 2h18a1 1 0 0 0 0-2ZM3 19h18a1 1 0 0 1 0 2H3a1 1 0 0 1 0-2Z"/></symbol>`;

export const EvoIconMenu24: EvoIconComponent = props => (
    <EvoIcon {...props} name="menu24" __symbol={SYMBOL} />
);
