import storyMarkupJson from "./story-markup.json";
import { urls } from "./common";

/**
 * Shape of `story-markup.json`, generated by
 * `packages/skin/scripts/storybook/extract-story-markup.ts` from every Skin
 * `.stories.js` file and committed to the repo (see `npm run build:story-markup -w
 * packages/skin`). Keyed by component (the story's top-level `src/sass` directory),
 * then by variant (derived from the story's title + export name).
 */
type StoryMarkupMap = Record<
  string,
  Record<string, { html: string; storybookId: string }>
>;

const storyMarkup = storyMarkupJson as StoryMarkupMap;

/**
 * Looks up a component's variant map, throwing if `story-markup.json` has no entry
 * for it. Throwing here (rather than returning undefined) turns a stale/mistyped
 * `component` reference into an immediate build failure instead of a silently
 * blank demo on the docs site.
 */
function getComponentEntry(component: string) {
  const componentEntry = storyMarkup[component];

  if (!componentEntry) {
    throw new Error(
      `story-markup.json has no entry for component="${component}". ` +
        `Run "npm run build:story-markup -w packages/skin" and check for a matching ` +
        `.stories.js title, or fix the typo in this page's reference.`,
    );
  }

  return componentEntry;
}

/** Same fail-fast behavior as {@link getComponentEntry}, scoped to one variant. */
function getVariantEntry(component: string, variant: string) {
  const variantEntry = getComponentEntry(component)[variant];

  if (!variantEntry) {
    throw new Error(
      `story-markup.json has no variant="${variant}" for component="${component}". ` +
        `Run "npm run build:story-markup -w packages/skin" and check for a matching ` +
        `.stories.js export, or fix the typo in this page's reference.`,
    );
  }

  return variantEntry;
}

/**
 * Returns `{ [variant]: html }` for every Storybook variant of `component`, e.g.
 * `getStoryMarkup("badge").empty` is the raw HTML string for Badge's "empty" story.
 * Used by `<component-demo>` to render live Storybook markup on docs pages without
 * hand-duplicating it.
 *
 * @param component - Component key, i.e. the directory name under
 *   `packages/skin/src/sass` (e.g. `"badge"`).
 * @returns A map of variant name to that story's rendered HTML string.
 * @throws If `component` has no entry in `story-markup.json`.
 */
export function getStoryMarkup(component: string): Record<string, string> {
  const componentEntry = getComponentEntry(component);
  const html: Record<string, string> = {};

  for (const variant in componentEntry) {
    html[variant] = componentEntry[variant].html;
  }

  return html;
}

/**
 * Returns the full clickable URL to `component`'s `variant` story in Storybook —
 * the pinned local dev port in development, the deployed static Storybook path in
 * production (see `skinStorybookUrl` in `./common`).
 *
 * @param component - Component key, i.e. the directory name under
 *   `packages/skin/src/sass` (e.g. `"badge"`).
 * @param variant - Variant name within that component (e.g. `"empty"`).
 * @returns The absolute Storybook URL for that exact story.
 * @throws If `component`/`variant` has no matching entry in `story-markup.json`.
 */
export function getStorybookUrl(component: string, variant: string): string {
  const { storybookId } = getVariantEntry(component, variant);
  return `${urls.skinStorybook}/?path=/story/${storybookId}`;
}
