name: eBay UI CI

on:
    pull_request:
        types: [opened, synchronize]
    push:
        branches: ["main", "[1-9][0-9].*"]

concurrency:
    group: "${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}"
    cancel-in-progress: true

permissions:
    actions: write
    checks: write
    contents: write
    deployments: write
    discussions: write
    issues: write
    packages: write
    id-token: write
    pull-requests: write
    repository-projects: write
    security-events: write
    statuses: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - run: npm i
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - run: npm run build:ci
            - uses: codecov/codecov-action@v5
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
    # Deployment job
    deploy:
        if: github.ref == 'refs/heads/main'
        # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
        permissions:
            pages: write
            id-token: write
            contents: write
            packages: write
            pull-requests: write
            issues: read
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
            - name: Install dependencies
              run: npm install
            - name: Deploy job
              run: npm run deploy
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
    release:
        # Sets permissions of the GITHUB_TOKEN to allow opening release PR
        needs: [deploy]
        permissions:
            id-token: write
            contents: write
            packages: write
            pull-requests: write
            issues: read
        runs-on: ubuntu-latest
        if: "${{ github.repository_owner == 'ebay' && github.event_name == 'push' }}"
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: "20"
                  cache: npm
            - name: Install dependencies
              run: npm i
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: Release
              id: changesets
              uses: changesets/action@v1
              with:
                  version: npm run version
                  publish: npm run release
                  commit: "ci: release"
                  title: "ci: release"
              env:
                  # Disable husky
                  HUSKY: 0
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
